name: test_email_only

on:
  workflow_dispatch: {}

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || \
          pip install selenium pytest python-dotenv webdriver-manager

      - name: Run pytest (capture console)
        env:
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}

          # Optional envs:
          HEADLESS: "true"
          ALWAYS_EMAIL: "true"
          EMAIL_ON_FAILURE: "true"
          USE_WEBDRIVER_MANAGER: "true"

        run: |
          set -o pipefail
          pytest -q test_claimsimple_email.py | tee smtp_console.log

      - name: Upload SMTP logs
        uses: actions/upload-artifact@v4
        with:
          name: smtp-logs
          path: smtp_console.log
          if-no-files-found: warn